# Generated by Django 5.1.6 on 2025-06-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='vast_url',
            field=models.URLField(blank=True, help_text='VAST URL for video ads', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='state',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted')], db_index=True, default='public', help_text='state of Media', max_length=20),
        ),
    ]
